Feature/terra3 50 alternat
it-objects/terraform-aws-terra3 pull request #15
Opened 2022-12-30 13:44 UTC by Kaushikkatariya

Please review PR request.
With multiple AZs, it has problem creating many elastic ips thus better to use alternat with only single AZ.

2023-01-16 13:53 UTC, w13k requested changes
Before working on the comments, let's discuss whether we still need this feature at all as alterNAT is targeted towards really large installations with huge outbound traffic.

2023-01-16 13:53 UTC, w13k commented on main.tf
> +  vpc_id                 = module.vpc.vpc_id
Please also add the case when VPC creation is deactivated and a VPC is already given. Currently, these lines indicate that only a Terra3-created VPC is supported

2023-01-16 13:53 UTC, w13k commented on main.tf
> +  create_alter_nat              = (var.nat == "ALTER_NAT") ? true : false
Bug: this also creates a NAT Gateway. See line 10. Maybe you can rewrite line 10 in a way that it's easier to understand and that future additions won't break with line 10.

2023-01-16 13:53 UTC, w13k commented on variables.tf
> +  description = "Select NO_NAT for no NAT, NAT_INSTANCES for NAT based on EC2 instances, NAT_GATEWAY for NAT with AWS NAT Gateways, or ALTER_NAT for hourly based EC2 instances."
Improve description: "... ALTERN_NAT for using the Open Source project AlterNAT for NAT."

2023-01-16 13:53 UTC, w13k commented on main.tf
> +  alternat_image_uri = "531874807515.dkr.ecr.eu-central-1.amazonaws.com/alternat"
Please use our public Docker account to publish the image, as this will incur cost on us. Or find an alternative solution.

2023-01-16 13:53 UTC, w13k commented on variables.tf
> +variable "ingress_security_group_ids" {
add prefix "alternat_" to variable name so that it becomes clear that this belongs to the alternat option.

2023-01-16 13:53 UTC, w13k commented on variables.tf
> +variable "nat_subnet_suffix" {
add prefix "alternat_" to variable name so that it becomes clear that this belongs to the alternat option.

2023-01-16 13:53 UTC, w13k commented on variables.tf
> +variable "tags" {
Can be removed from here and from the alternat module declaration.

2023-01-18 14:36 UTC, closed without merging

2023-01-18 14:37 UTC, Kaushikkatariya commented
This feature is not required as of now. Since this feature is useful for only larger infrastructures.