Feature/terra3 51 scheduled https api call
it-objects/terraform-aws-terra3 pull request #18
Opened 2023-01-12 08:46 UTC by Kaushikkatariya

Please review my PR.

2023-01-13 09:03 UTC, w13k requested changes

2023-01-13 09:03 UTC, w13k commented on main.tf
> +module "eventbridge" {
Please move up everything into the scheduled_api_call module. It is there anyway and at a later stage we plan to allow 1 to many scheduled api calls.

2023-01-13 09:03 UTC, w13k commented on main.tf
> +  local_existing_package = data.archive_file.function[0].output_path
Don't create the zip by yourself with data.archive_file but rather use what's already given by the lambda module, namely the "source_path". Move up the index.js as well into the scheduled_api_call folder and rename it to something more self-explaining, e.g. api_call.js

2023-01-13 09:03 UTC, w13k commented on variables.tf
>      error_message = "Only max. 16 lower-case alphanumeric characters and dashes in between are allowed."
26 or 16? Currently, the condition and the description do not match.

2023-01-13 09:03 UTC, w13k commented on examples/scheduled_api_call/main.tf
> +# ---------------------------------------------------------------------------------------------------------------------
Before working on the feedback, please pull the branch as I've pushed already some slights refactorings by myself!

2023-01-16 13:56 UTC, Kaushikkatariya commented on main.tf
> +module "eventbridge" {
Done

2023-01-16 13:56 UTC, Kaushikkatariya commented on main.tf
> +  local_existing_package = data.archive_file.function[0].output_path
done

2023-01-16 13:59 UTC, Kaushikkatariya commented on main.tf
> +module "eventbridge" {
I have disabled module "scheduled_api_call" in modules/scheduled_api_call, as it requires the api_key.

2023-01-16 14:37 UTC, w13k approved these changes

2023-01-16 16:20 UTC, w13k reviewed
When running the example, I get this error message. Can you please have a look?

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/7670605/212724315-88a5c62e-5972-4631-87c8-1606fab9db5c.png">

2023-01-17 12:50 UTC, merged

2023-01-17 12:51 UTC, w13k commented
This PR is included in version 0.12.0 :tada: