Feature/terra3 108 environment hibernation mini admin website
it-objects/terraform-aws-terra3 pull request #37
Opened 2023-08-02 15:32 UTC by Kaushikkatariya

Please review my PR.

2023-08-14 12:16 UTC, w13k requested changes

2023-08-14 12:16 UTC, w13k commented on modules/global_scale_down/main.tf
> +data "template_file" "index" {
Using template_file with the template file provider is deprecated and should not be used anymore. See https://registry.terraform.io/providers/hashicorp/template/latest/docs/data-sources/file Use templatefile instead as described on the webpage.

2023-08-14 12:16 UTC, w13k commented on modules/cloudfront_cdn/main.tf
> +      path_pattern           = "/admin/*"
path_pattern needs to made configurable. Please default to "/admin/terra3/*"

2023-08-14 12:16 UTC, w13k commented on modules/cloudfront_cdn/main.tf
> +      path_pattern           = "/admin/*"
/admin/* is often used for application's admin page

2023-08-14 12:16 UTC, w13k commented on modules/cloudfront_cdn/main.tf
When entering https://terra3-example3.aws-sandbox.it-objects.de/admin/, I'd like to see the admin page. I don't want to type in the whole https://terra3-example3.aws-sandbox.it-objects.de/admin/index.html as it is required by now.

2023-08-14 12:16 UTC, w13k commented on modules/cloudfront_cdn/main.tf
When stopping with DB, it takes a long time to make it happen. During the stopping time, when I hit "Status", I receive the status "scaled_up". I'd like to receive the status "scaling_down" if possible during that period of time.

2023-08-14 12:16 UTC, w13k commented on modules/cloudfront_cdn/main.tf
With example3 I get this error message when trying to scale down:

2023-08-14T12:03:32.531Z	54a34889-8abf-47b0-b0f0-b3b6afc75997	ERROR	Error updating ECS services: AccessDeniedException: User: arn:aws:sts::531874807515:assumed-role/terra3-example3-global-scale-down/terra3-example3-global-scale-down is not authorized to perform: ssm:PutParameter on resource: arn:aws:ssm:eu-central-1:531874807515:parameter/terra3-example3/global_scale_down/ecs_service_data because no identity-based policy allows the ssm:PutParameter action
    at throwDefaultError (/var/runtime/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at deserializeAws_json1_1PutParameterCommandError (/var/runtime/node_modules/@aws-sdk/client-ssm/dist-cjs/protocols/Aws_json1_1.js:5720:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/runtime/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /var/runtime/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:13:20
    at async StandardRetryStrategy.retry (/var/runtime/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async scale_down_handler (file:///var/task/scale_down.mjs:228:13)
    at async Runtime.handler (file:///var/task/scale_down.mjs:18:9) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '34095bad-9a88-479f-879c-73142171dea5',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  __type: 'AccessDeniedException'
}

2023-08-14 12:16 UTC, w13k commented on modules/cloudfront_cdn/main.tf
Set the Lambda Logs and any logs in general to a max retention time of one month.

2023-08-27 15:14 UTC, Kaushikkatariya commented on modules/global_scale_down/main.tf
> +data "template_file" "index" {
template_file has been updated as a function.

2023-08-28 11:47 UTC, Kaushikkatariya commented on modules/cloudfront_cdn/main.tf
> +      path_pattern           = "/admin/*"
/admin-terra3/index.html = /admin-terra3/

2023-08-28 11:48 UTC, Kaushikkatariya commented on modules/cloudfront_cdn/main.tf
> +      path_pattern           = "/admin/*"
No path pattern configuration.

2023-08-28 15:00 UTC, Kaushikkatariya commented on modules/cloudfront_cdn/main.tf
cloudwatch_logs_retention_in_days is set to 30
/admin-terra3/index.html = /admin-terra3/ is implemented now

2023-08-28 20:10 UTC, Kaushikkatariya commented on modules/cloudfront_cdn/main.tf
implemented scaling_up and scaling_down
Only need to code review the last time and final testing previous and latest changes.

2023-11-28 12:42 UTC, w13k approved these changes
Hey Kaushik, lgtm! Please go ahead with the merge yourself once ready.

2023-11-28 12:42 UTC, w13k commented on modules/app_component/main.tf
.mjs has been added accidentally to the keyword "down". To be removed.

2023-11-28 14:30 UTC, Kaushikkatariya commented on modules/app_component/main.tf
Removed.

2023-11-28 14:37 UTC, merged

2023-11-28 14:38 UTC, w13k commented
This PR is included in version 1.30.0 :tada: